service: auction-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2

functions:
  createAuction:
    handler: handler.createAuction
    events:
      - http:
          method: POST
          path: /auction

plugins:
  - serverless-esbuild
