service: auction-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Query
      Resource:
        - ${self:custom.AuctionsTable.arn}
        - !Join ['/', ['${self:custom.AuctionsTable.arn}', 'index', 'statusAndEndDate']]

resources:
  Resources:
    AuctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: endingAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: statusAndEndDate
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: endingAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

functions:
  createAuction:
    handler: handler.createAuctionHandler
    events:
      - http:
          method: POST
          path: /auction
          authorizer: ${self:custom.authorizerArn}
  getAuctions:
    handler: handler.getAuctionsHandler
    events:
      - http:
          method: GET
          path: /auctions
          authorizer: ${self:custom.authorizerArn}
  getAuctionsById:
    handler: handler.getAuctionsByIdHandler
    events:
      - http:
          method: GET
          path: /auctions/{id}
          authorizer: ${self:custom.authorizerArn}
  placeBid:
    handler: handler.placeBidHandler
    events:
      - http:
          method: PATCH
          path: /auctions/{id}/bid
          authorizer: ${self:custom.authorizerArn}
  processAuctions:
    handler: handler.processAuctionsHandler
    events:
      - schedule: rate(1 minute)


plugins:
  - serverless-esbuild

custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  authorizerArn: arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:auth-service-${self:provider.stage}-auth
